Scene managment
Rdzawa-Wewerka/GingerWorld pull request #2
Opened 2023-07-19 20:33 UTC by jaanonim

2023-07-19 20:49 UTC, n2oneProgrammer requested changes

2023-07-19 20:49 UTC, n2oneProgrammer commented on Assets/Editor/SceneWindow.cs
> +        var guids = AssetDatabase.FindAssets("t:" + typeof(ScenesPreset).Name);
I do not think var is good idea, because I do not know what is this type

2023-07-19 20:49 UTC, n2oneProgrammer commented on Assets/Scripts/Managers/SectorManager.cs
> +using System.Collections;
it is empty class

2023-07-19 20:49 UTC, Mimilo13 approved these changes

2023-07-19 20:52 UTC, jaanonim commented on Assets/Scripts/Managers/SectorManager.cs
> +using System.Collections;
It's a placeholder, it will ne implemented i futhure. Btw GameManager is also empty :-)

2023-07-19 22:06 UTC, Dudek03 commented on Assets/Docs/StyleGuides.md
> +    - if you require same other component on the same game object use `[RequireComponent(typeof(Sth))]`
?

2023-07-19 23:25 UTC, Dudek03 commented on Assets/Scripts/LoadSceneOnStart.cs
> +#if !UNITY_EDITOR
co to za if

2023-07-19 23:42 UTC, Dudek03 reviewed
explain

2023-07-20 19:54 UTC, n2oneProgrammer approved these changes
LGTM

2023-07-20 19:55 UTC, merged